# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAMetro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LAMetro
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper', '~> 2.0'
  pod 'AlamofireObjectMapper', '~> 4.0.0'
  pod 'DZNEmptyDataSet'
  pod 'RealmSwift'

end
